<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Validation\Rule;

class StoreShopRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $regex = '/^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/';
        return [
            'name' => ['required', 'unique:shops', 'min:7', 'max:255'],
            'description' => ['nullable', 'min:10'],
            'address' => ['nullable'],
            'phone_number' => ['nullable', 'regex:' . $regex],
            'email' => ['required', 'email:rfc,dns', Rule::unique('shops')],
            'rating' => ['nullable'],
            'manager_name' => ['required', 'min:7', 'max:255']
        ];
    }

    public function failedValidation(Validator $validator)
    {
//        parent::failedValidation($validator); // TODO: Change the autogenerated stub
        throw new HttpResponseException(response()->json([
            'success' => false,
            'message' => 'Validation errors',
            'data' => $validator->errors()
        ]));
    }
}
